version: "3.9"

services:

  db:
    image: postgres:15
    container_name: ithousecourse_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-myproject}
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypassword}
      POSTGRES_PORT: ${DB_PORT:-5432}
    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U $DB_USER -d $DB_NAME" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis
    container_name: ithouseonline_redis
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ithouseonline_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - TZ=Asia/Tashkent
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  static_volume:
  media_volume:
